export const SET_USER='SET_USER';
export const SET_ERROR = 'SET_ERROR';
export const GET_PROFILE = 'GET_PROFILE';

export const GET_ERRORS = "GET_ERRORS"
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILES = "GET_PROFILES";
export const GET_OTHERUSER_PROFILE = "GET_OTHERUSER_PROFILE";
